# Generated by Django 3.1.6 on 2021-02-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_destination_destinationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='radius',
            field=models.PositiveIntegerField(default=8, help_text='В метрах', verbose_name='Радиус области входа'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
