# Generated by Django 3.1.6 on 2021-02-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_auto_20210218_0118'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(fields=('title', 'longitude', 'latitude'), name='unique_destination'),
        ),
    ]
