# Generated by Django 3.1.6 on 2021-02-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_auto_20210218_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное изображение/фото, представляющее маршрут.', null=True, upload_to='route_headers/', verbose_name='Изображение'),
        ),
    ]
