# Generated by Django 3.1.6 on 2021-02-17 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_auto_20210218_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='route',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='routes.route'),
            preserve_default=False,
        ),
    ]
