# Generated by Django 3.1.6 on 2021-02-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_auto_20210218_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('simple', 'Простая точка'), ('sight', 'Достопримечательность'), ('monument', 'Памятник'), ('important', 'Важное')], max_length=16, verbose_name='Тип'),
        ),
    ]
