# Generated by Django 3.1.6 on 2021-03-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20210308_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Долгота'),
        ),
    ]
