# Generated by Django 3.1.6 on 2021-03-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('routes', '0014_auto_20210308_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waypoint',
            options={'ordering': ['index'], 'verbose_name': 'Путевая точка', 'verbose_name_plural': 'Путевые точки'},
        ),
        migrations.AddField(
            model_name='waypoint',
            name='index',
            field=models.PositiveIntegerField(help_text='Порядковый номер путевой точки в маршруте',
                                              verbose_name='Индекс', null=True),
            # preserve_default=False,
        ),
        # migrations.AddConstraint(
        #     model_name='waypoint',
        #     constraint=models.UniqueConstraint(fields=('index', 'route'), name='unique_route_waypoint_index'),
        # ),
    ]
