# Generated by Django 3.1.6 on 2021-03-10 07:21
import time

from django.db import migrations


def generate_index(apps, schema_editor):
    Waypoint = apps.get_model('routes', 'Waypoint')
    for row in Waypoint.objects.all():
        row.index = round((time.time() * 1000) % 100000000)
        row.save(update_fields=['index'])


class Migration(migrations.Migration):
    dependencies = [
        ('routes', '0015_add_waypoint_index_field'),
    ]

    operations = [
        migrations.RunPython(generate_index, reverse_code=migrations.RunPython.noop)
    ]
