# Generated by Django 3.1.6 on 2021-03-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0016_populate_index_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='index',
            field=models.PositiveIntegerField(help_text='Порядковый номер путевой точки в маршруте',
                                              verbose_name='Индекс'),
            # preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='waypoint',
            constraint=models.UniqueConstraint(fields=('index', 'route'), name='unique_route_waypoint_index'),
        ),
    ]
