# Generated by Django 3.1.6 on 2021-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0017_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='short_description',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Короткое описание'),
        ),
    ]
